---
title: "DATA_PREP_BCI_SURVIVAL"
author: "Alexandra Thiel"
date: "2023-10-23"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(data.table)
library(tidyverse)
library(lubridate)
library(readxl)
library(ggeffects)
library(mgcv)
```

```{r data}

CAP <- read_excel("./DATA/Bear_data_2022.xlsx", sheet = 1)

MEAS <- read_excel("./DATA/Bear_data_2022.xlsx", sheet = 2)

AGE <- read_excel("./DATA/Bear_data_2022.xlsx", sheet = 4)

```

```{r prep capture data}

CAP1 <- CAP %>% 
  filter(!ReasonImmob == "Marking Attempt Aborted",
         !(is.na(NrHits) & is.na(NrDarts) & Antidot == 0)) %>% 
  droplevels() %>% 
  arrange(BearID, MarkingDate) %>% 
  group_by(BearID) %>% 
  mutate(NrCapture = row_number(BearID),
         Capture_yday = yday(MarkingDate)) %>% 
  dplyr::select(BearID, MarkingDate, NrCapture, ReasonImmob, MarkingID, Capture_yday)

```

```{r prep measurement data}

MEAS1 <- MEAS %>% 
  dplyr::select(BearID, DateMeasure, Chest, BodyLength, FrontFot, BackFootLength, Fat, LifeWeight, MarkingId) %>% 
  rename(MarkingDate = DateMeasure,
         MarkingID = MarkingId)

```

```{r prep age data}

AGE1 <- AGE %>% 
  dplyr::select(BearID, Sex, Birth)

```

```{r merge all data}

MERGED <- CAP1 %>% 
  inner_join(MEAS1) %>% 
  inner_join(AGE1)

MERGED1 <- MERGED %>% 
  filter(!is.na(LifeWeight), !is.na(BodyLength), !is.na(Birth)) %>% 
  mutate(LifeWeight = as.numeric(LifeWeight),
         BodyLength = as.numeric(BodyLength),
         Birth = as.numeric(Birth)) %>% 
  mutate(lnBW = log(LifeWeight), 
         lnBL = log(BodyLength),
         Age = year(MarkingDate) - Birth) %>% 
  filter(!lnBW == "-Inf", !lnBL == "-Inf") %>% 
  filter(!c(LifeWeight >= 50 & BodyLength <= 125)) %>% 
  mutate(Winter_Spring = case_when(ReasonImmob == "Hibernation/blood sampling" ~ "Winter_Summer", TRUE ~ "Spring"))

```

```{r perform linear regression}

# ln(BW) = a + b * ln(BL)

MERGED1 %>% 
  ggplot()+
  geom_point(aes(x = lnBW, y = lnBL))+
  geom_smooth(aes(x = lnBW, y = lnBL), method = "lm")

m <- lm(lnBW ~ lnBL,
        data = MERGED1)

sum_m <- summary(m)

plot(ggpredict(m))

# Where 'a' and 'b' are the intercept and slope of the regression line, respectively.
# 
# Calculate the standardized residual:
# 
# Plug the ln(BL) of the specific bear (in this case, ln(185) ≈ 5.220) into the regression equation.

# ln(BW) = a + b * ln(BL)

MERGED1 <- MERGED1 %>% 
  mutate(PredLnBW = m$coefficients[1] + m$coefficients[2] * lnBL)

# Calculate the standardized residual (z-score) using the formula:
# 
# z = (Observed ln(BW) - Predicted ln(BW)) / Standard error of ln(BW)

MERGED1 <- MERGED1 %>% 
  mutate(BCI = (lnBW - PredLnBW)/sum_m$coefficients[1,2])

# 
# The "Observed ln(BW)" is the ln(BW) of the specific bear (ln(138) ≈ 4.927), and the "Predicted ln(BW)" is what you get from the regression equation.
# 
# The "Standard deviation of ln(BW)" is the standard deviation of ln(BW) from the sample used for the regression.
# 
# The standardized residual is the Body Condition Index (BCI):
# 
# The BCI will tell you how the bear's body weight compares to what would be expected for its body size, based on the regression equation. If the BCI is positive, it means the bear is in better condition than expected for its size. If it's negative, it's in poorer condition than expected.


```

```{r explore}

# relationship between Age and BCI
MERGED1 %>% 
  ggplot()+
  geom_point(aes(x = Age, y = BCI))

# density of BCI
MERGED1 %>% 
  ggplot()+
  geom_density(aes(x = BCI))

```

```{r explore with frequentist model}

DF <- MERGED1 %>% 
  #filter(between(BCI, -5, 5)) %>% 
  mutate(BearID = as.factor(BearID)) %>% 
  mutate(Capture_month = month(MarkingDate),
         Capture_Season = case_when(Capture_month %in% c(2,3) ~ "Winter",
                                    Capture_month %in% c(6) & ReasonImmob == "Hibernation/blood sampling" ~ "Summer", TRUE ~ "Spring"))

fwrite(DF, "./DATA/BCI_CAPTURED.dat")

m1 <- gam(BCI ~ NrCapture + Age + Capture_yday + Capture_Season + s(BearID, bs = "re"), 
          data = DF)

plot(ggpredict(m1))

summary(m1)

```

